$env:SUPABASE_DB_URL="jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0"
$env:SUPABASE_DB_USER="postgres.lbzcfhavzhfmeqjncsno"
$env:SUPABASE_DB_PASSWORD="thanhbinh13405@"
$env:SUPABASE_URL="https://lbzcfhavzhfmeqjncsno.supabase.co"
$env:SUPABASE_SERVICE_ROLE_KEY="sb_secret_LueCnSzHYBpMbIAJ1m_KIg_j2UG_ygd"
$env:SUPABASE_STORAGE_BUCKET="feedback-images"
$env:GROQ_API_KEYS="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,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,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,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"
$env:DEEPSEEK_API_KEY="sk-bafff4258e7a4b12a79fdca36504be73"

$env:GEMINI_API_KEYS="AQ.Ab8RN6I8P4_1wL3_VFSY8SvKM15neM9GwhLMvZCsUSIXKfm95g"
