$env:SUPABASE_DB_URL="jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0"
$env:SUPABASE_DB_USER="postgres.lbzcfhavzhfmeqjncsno"
$env:SUPABASE_DB_PASSWORD="thanhbinh13405@"
$env:SUPABASE_URL="https://lbzcfhavzhfmeqjncsno.supabase.co"
$env:SUPABASE_SERVICE_ROLE_KEY="sb_secret_LueCnSzHYBpMbIAJ1m_KIg_j2UG_ygd"
$env:SUPABASE_STORAGE_BUCKET="feedback-images"
