ALTER TABLE users ADD COLUMN IF NOT EXISTS is_campaign_banned BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_campaign_unban_at TIMESTAMP WITHOUT TIME ZONE;

CREATE TABLE IF NOT EXISTS campaign_appeals (
    id BIGSERIAL PRIMARY KEY,
    citizen_id BIGINT NOT NULL REFERENCES users(id),
    reason VARCHAR(1000) NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING' NOT NULL,
    reviewed_by_id BIGINT REFERENCES users(id),
    review_notes VARCHAR(1000),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);
