/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthorityLoginRouteImport } from './routes/authority-login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyReportsIndexRouteImport } from './routes/my-reports.index'
import { Route as MyReportsIdRouteImport } from './routes/my-reports.$id'
import { Route as AuthWardRouteImport } from './routes/_auth.ward'
import { Route as AuthPoliceRouteImport } from './routes/_auth.police'
import { Route as AuthCityAdminRouteImport } from './routes/_auth.city-admin'
import { Route as AuthAssistantRouteImport } from './routes/_auth.assistant'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityLoginRoute = AuthorityLoginRouteImport.update({
  id: '/authority-login',
  path: '/authority-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportsIndexRoute = MyReportsIndexRouteImport.update({
  id: '/my-reports/',
  path: '/my-reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportsIdRoute = MyReportsIdRouteImport.update({
  id: '/my-reports/$id',
  path: '/my-reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWardRoute = AuthWardRouteImport.update({
  id: '/ward',
  path: '/ward',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPoliceRoute = AuthPoliceRouteImport.update({
  id: '/police',
  path: '/police',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCityAdminRoute = AuthCityAdminRouteImport.update({
  id: '/city-admin',
  path: '/city-admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAssistantRoute = AuthAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authority-login': typeof AuthorityLoginRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assistant': typeof AuthAssistantRoute
  '/city-admin': typeof AuthCityAdminRoute
  '/police': typeof AuthPoliceRoute
  '/ward': typeof AuthWardRoute
  '/my-reports/$id': typeof MyReportsIdRoute
  '/my-reports/': typeof MyReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authority-login': typeof AuthorityLoginRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assistant': typeof AuthAssistantRoute
  '/city-admin': typeof AuthCityAdminRoute
  '/police': typeof AuthPoliceRoute
  '/ward': typeof AuthWardRoute
  '/my-reports/$id': typeof MyReportsIdRoute
  '/my-reports': typeof MyReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/authority-login': typeof AuthorityLoginRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_auth/assistant': typeof AuthAssistantRoute
  '/_auth/city-admin': typeof AuthCityAdminRoute
  '/_auth/police': typeof AuthPoliceRoute
  '/_auth/ward': typeof AuthWardRoute
  '/my-reports/$id': typeof MyReportsIdRoute
  '/my-reports/': typeof MyReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authority-login'
    | '/login'
    | '/register'
    | '/report'
    | '/sitemap.xml'
    | '/assistant'
    | '/city-admin'
    | '/police'
    | '/ward'
    | '/my-reports/$id'
    | '/my-reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authority-login'
    | '/login'
    | '/register'
    | '/report'
    | '/sitemap.xml'
    | '/assistant'
    | '/city-admin'
    | '/police'
    | '/ward'
    | '/my-reports/$id'
    | '/my-reports'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/authority-login'
    | '/login'
    | '/register'
    | '/report'
    | '/sitemap.xml'
    | '/_auth/assistant'
    | '/_auth/city-admin'
    | '/_auth/police'
    | '/_auth/ward'
    | '/my-reports/$id'
    | '/my-reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthorityLoginRoute: typeof AuthorityLoginRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MyReportsIdRoute: typeof MyReportsIdRoute
  MyReportsIndexRoute: typeof MyReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority-login': {
      id: '/authority-login'
      path: '/authority-login'
      fullPath: '/authority-login'
      preLoaderRoute: typeof AuthorityLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reports/': {
      id: '/my-reports/'
      path: '/my-reports'
      fullPath: '/my-reports/'
      preLoaderRoute: typeof MyReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reports/$id': {
      id: '/my-reports/$id'
      path: '/my-reports/$id'
      fullPath: '/my-reports/$id'
      preLoaderRoute: typeof MyReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/ward': {
      id: '/_auth/ward'
      path: '/ward'
      fullPath: '/ward'
      preLoaderRoute: typeof AuthWardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/police': {
      id: '/_auth/police'
      path: '/police'
      fullPath: '/police'
      preLoaderRoute: typeof AuthPoliceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/city-admin': {
      id: '/_auth/city-admin'
      path: '/city-admin'
      fullPath: '/city-admin'
      preLoaderRoute: typeof AuthCityAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/assistant': {
      id: '/_auth/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthAssistantRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAssistantRoute: typeof AuthAssistantRoute
  AuthCityAdminRoute: typeof AuthCityAdminRoute
  AuthPoliceRoute: typeof AuthPoliceRoute
  AuthWardRoute: typeof AuthWardRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAssistantRoute: AuthAssistantRoute,
  AuthCityAdminRoute: AuthCityAdminRoute,
  AuthPoliceRoute: AuthPoliceRoute,
  AuthWardRoute: AuthWardRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthorityLoginRoute: AuthorityLoginRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MyReportsIdRoute: MyReportsIdRoute,
  MyReportsIndexRoute: MyReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
