/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WardRouteImport } from './routes/ward'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PoliceRouteImport } from './routes/police'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CityAdminRouteImport } from './routes/city-admin'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyReportsIndexRouteImport } from './routes/my-reports.index'
import { Route as MyReportsIdRouteImport } from './routes/my-reports.$id'

const WardRoute = WardRouteImport.update({
  id: '/ward',
  path: '/ward',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliceRoute = PoliceRouteImport.update({
  id: '/police',
  path: '/police',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CityAdminRoute = CityAdminRouteImport.update({
  id: '/city-admin',
  path: '/city-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportsIndexRoute = MyReportsIndexRouteImport.update({
  id: '/my-reports/',
  path: '/my-reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportsIdRoute = MyReportsIdRouteImport.update({
  id: '/my-reports/$id',
  path: '/my-reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/city-admin': typeof CityAdminRoute
  '/login': typeof LoginRoute
  '/police': typeof PoliceRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ward': typeof WardRoute
  '/my-reports/$id': typeof MyReportsIdRoute
  '/my-reports/': typeof MyReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/city-admin': typeof CityAdminRoute
  '/login': typeof LoginRoute
  '/police': typeof PoliceRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ward': typeof WardRoute
  '/my-reports/$id': typeof MyReportsIdRoute
  '/my-reports': typeof MyReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/city-admin': typeof CityAdminRoute
  '/login': typeof LoginRoute
  '/police': typeof PoliceRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ward': typeof WardRoute
  '/my-reports/$id': typeof MyReportsIdRoute
  '/my-reports/': typeof MyReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/city-admin'
    | '/login'
    | '/police'
    | '/report'
    | '/sitemap.xml'
    | '/ward'
    | '/my-reports/$id'
    | '/my-reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/city-admin'
    | '/login'
    | '/police'
    | '/report'
    | '/sitemap.xml'
    | '/ward'
    | '/my-reports/$id'
    | '/my-reports'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/city-admin'
    | '/login'
    | '/police'
    | '/report'
    | '/sitemap.xml'
    | '/ward'
    | '/my-reports/$id'
    | '/my-reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  CityAdminRoute: typeof CityAdminRoute
  LoginRoute: typeof LoginRoute
  PoliceRoute: typeof PoliceRoute
  ReportRoute: typeof ReportRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WardRoute: typeof WardRoute
  MyReportsIdRoute: typeof MyReportsIdRoute
  MyReportsIndexRoute: typeof MyReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ward': {
      id: '/ward'
      path: '/ward'
      fullPath: '/ward'
      preLoaderRoute: typeof WardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/police': {
      id: '/police'
      path: '/police'
      fullPath: '/police'
      preLoaderRoute: typeof PoliceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city-admin': {
      id: '/city-admin'
      path: '/city-admin'
      fullPath: '/city-admin'
      preLoaderRoute: typeof CityAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reports/': {
      id: '/my-reports/'
      path: '/my-reports'
      fullPath: '/my-reports/'
      preLoaderRoute: typeof MyReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reports/$id': {
      id: '/my-reports/$id'
      path: '/my-reports/$id'
      fullPath: '/my-reports/$id'
      preLoaderRoute: typeof MyReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  CityAdminRoute: CityAdminRoute,
  LoginRoute: LoginRoute,
  PoliceRoute: PoliceRoute,
  ReportRoute: ReportRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WardRoute: WardRoute,
  MyReportsIdRoute: MyReportsIdRoute,
  MyReportsIndexRoute: MyReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
