/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as TinTucRouteImport } from './routes/tin-tuc'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportRouteImport } from './routes/report'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedbackSearchRouteImport } from './routes/feedback-search'
import { Route as AuthorityLoginRouteImport } from './routes/authority-login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyReportsIndexRouteImport } from './routes/my-reports.index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns.index'
import { Route as MyReportsIdRouteImport } from './routes/my-reports.$id'
import { Route as CampaignsCreateRouteImport } from './routes/campaigns.create'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as AuthWardRouteImport } from './routes/_auth.ward'
import { Route as AuthPoliceRouteImport } from './routes/_auth.police'
import { Route as AuthCityAdminRouteImport } from './routes/_auth.city-admin'
import { Route as AuthAssistantRouteImport } from './routes/_auth.assistant'
import { Route as CampaignsIdGroupChatRouteImport } from './routes/campaigns.$id.group-chat'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const TinTucRoute = TinTucRouteImport.update({
  id: '/tin-tuc',
  path: '/tin-tuc',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackSearchRoute = FeedbackSearchRouteImport.update({
  id: '/feedback-search',
  path: '/feedback-search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityLoginRoute = AuthorityLoginRouteImport.update({
  id: '/authority-login',
  path: '/authority-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportsIndexRoute = MyReportsIndexRouteImport.update({
  id: '/my-reports/',
  path: '/my-reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportsIdRoute = MyReportsIdRouteImport.update({
  id: '/my-reports/$id',
  path: '/my-reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCreateRoute = CampaignsCreateRouteImport.update({
  id: '/campaigns/create',
  path: '/campaigns/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWardRoute = AuthWardRouteImport.update({
  id: '/ward',
  path: '/ward',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPoliceRoute = AuthPoliceRouteImport.update({
  id: '/police',
  path: '/police',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCityAdminRoute = AuthCityAdminRouteImport.update({
  id: '/city-admin',
  path: '/city-admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAssistantRoute = AuthAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthRoute,
} as any)
const CampaignsIdGroupChatRoute = CampaignsIdGroupChatRouteImport.update({
  id: '/group-chat',
  path: '/group-chat',
  getParentRoute: () => CampaignsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authority-login': typeof AuthorityLoginRoute
  '/feedback-search': typeof FeedbackSearchRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tin-tuc': typeof TinTucRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/assistant': typeof AuthAssistantRoute
  '/city-admin': typeof AuthCityAdminRoute
  '/police': typeof AuthPoliceRoute
  '/ward': typeof AuthWardRoute
  '/campaigns/$id': typeof CampaignsIdRouteWithChildren
  '/campaigns/create': typeof CampaignsCreateRoute
  '/my-reports/$id': typeof MyReportsIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/my-reports/': typeof MyReportsIndexRoute
  '/campaigns/$id/group-chat': typeof CampaignsIdGroupChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authority-login': typeof AuthorityLoginRoute
  '/feedback-search': typeof FeedbackSearchRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tin-tuc': typeof TinTucRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/assistant': typeof AuthAssistantRoute
  '/city-admin': typeof AuthCityAdminRoute
  '/police': typeof AuthPoliceRoute
  '/ward': typeof AuthWardRoute
  '/campaigns/$id': typeof CampaignsIdRouteWithChildren
  '/campaigns/create': typeof CampaignsCreateRoute
  '/my-reports/$id': typeof MyReportsIdRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/my-reports': typeof MyReportsIndexRoute
  '/campaigns/$id/group-chat': typeof CampaignsIdGroupChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/authority-login': typeof AuthorityLoginRoute
  '/feedback-search': typeof FeedbackSearchRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/report': typeof ReportRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tin-tuc': typeof TinTucRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_auth/assistant': typeof AuthAssistantRoute
  '/_auth/city-admin': typeof AuthCityAdminRoute
  '/_auth/police': typeof AuthPoliceRoute
  '/_auth/ward': typeof AuthWardRoute
  '/campaigns/$id': typeof CampaignsIdRouteWithChildren
  '/campaigns/create': typeof CampaignsCreateRoute
  '/my-reports/$id': typeof MyReportsIdRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/my-reports/': typeof MyReportsIndexRoute
  '/campaigns/$id/group-chat': typeof CampaignsIdGroupChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authority-login'
    | '/feedback-search'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/report'
    | '/sitemap.xml'
    | '/tin-tuc'
    | '/verify-otp'
    | '/assistant'
    | '/city-admin'
    | '/police'
    | '/ward'
    | '/campaigns/$id'
    | '/campaigns/create'
    | '/my-reports/$id'
    | '/campaigns/'
    | '/my-reports/'
    | '/campaigns/$id/group-chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authority-login'
    | '/feedback-search'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/report'
    | '/sitemap.xml'
    | '/tin-tuc'
    | '/verify-otp'
    | '/assistant'
    | '/city-admin'
    | '/police'
    | '/ward'
    | '/campaigns/$id'
    | '/campaigns/create'
    | '/my-reports/$id'
    | '/campaigns'
    | '/my-reports'
    | '/campaigns/$id/group-chat'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/authority-login'
    | '/feedback-search'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/report'
    | '/sitemap.xml'
    | '/tin-tuc'
    | '/verify-otp'
    | '/_auth/assistant'
    | '/_auth/city-admin'
    | '/_auth/police'
    | '/_auth/ward'
    | '/campaigns/$id'
    | '/campaigns/create'
    | '/my-reports/$id'
    | '/campaigns/'
    | '/my-reports/'
    | '/campaigns/$id/group-chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthorityLoginRoute: typeof AuthorityLoginRoute
  FeedbackSearchRoute: typeof FeedbackSearchRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportRoute: typeof ReportRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TinTucRoute: typeof TinTucRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  CampaignsIdRoute: typeof CampaignsIdRouteWithChildren
  CampaignsCreateRoute: typeof CampaignsCreateRoute
  MyReportsIdRoute: typeof MyReportsIdRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  MyReportsIndexRoute: typeof MyReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin-tuc': {
      id: '/tin-tuc'
      path: '/tin-tuc'
      fullPath: '/tin-tuc'
      preLoaderRoute: typeof TinTucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback-search': {
      id: '/feedback-search'
      path: '/feedback-search'
      fullPath: '/feedback-search'
      preLoaderRoute: typeof FeedbackSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority-login': {
      id: '/authority-login'
      path: '/authority-login'
      fullPath: '/authority-login'
      preLoaderRoute: typeof AuthorityLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reports/': {
      id: '/my-reports/'
      path: '/my-reports'
      fullPath: '/my-reports/'
      preLoaderRoute: typeof MyReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-reports/$id': {
      id: '/my-reports/$id'
      path: '/my-reports/$id'
      fullPath: '/my-reports/$id'
      preLoaderRoute: typeof MyReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/create': {
      id: '/campaigns/create'
      path: '/campaigns/create'
      fullPath: '/campaigns/create'
      preLoaderRoute: typeof CampaignsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/ward': {
      id: '/_auth/ward'
      path: '/ward'
      fullPath: '/ward'
      preLoaderRoute: typeof AuthWardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/police': {
      id: '/_auth/police'
      path: '/police'
      fullPath: '/police'
      preLoaderRoute: typeof AuthPoliceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/city-admin': {
      id: '/_auth/city-admin'
      path: '/city-admin'
      fullPath: '/city-admin'
      preLoaderRoute: typeof AuthCityAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/assistant': {
      id: '/_auth/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthAssistantRouteImport
      parentRoute: typeof AuthRoute
    }
    '/campaigns/$id/group-chat': {
      id: '/campaigns/$id/group-chat'
      path: '/group-chat'
      fullPath: '/campaigns/$id/group-chat'
      preLoaderRoute: typeof CampaignsIdGroupChatRouteImport
      parentRoute: typeof CampaignsIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAssistantRoute: typeof AuthAssistantRoute
  AuthCityAdminRoute: typeof AuthCityAdminRoute
  AuthPoliceRoute: typeof AuthPoliceRoute
  AuthWardRoute: typeof AuthWardRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAssistantRoute: AuthAssistantRoute,
  AuthCityAdminRoute: AuthCityAdminRoute,
  AuthPoliceRoute: AuthPoliceRoute,
  AuthWardRoute: AuthWardRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface CampaignsIdRouteChildren {
  CampaignsIdGroupChatRoute: typeof CampaignsIdGroupChatRoute
}

const CampaignsIdRouteChildren: CampaignsIdRouteChildren = {
  CampaignsIdGroupChatRoute: CampaignsIdGroupChatRoute,
}

const CampaignsIdRouteWithChildren = CampaignsIdRoute._addFileChildren(
  CampaignsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthorityLoginRoute: AuthorityLoginRoute,
  FeedbackSearchRoute: FeedbackSearchRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportRoute: ReportRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TinTucRoute: TinTucRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  CampaignsIdRoute: CampaignsIdRouteWithChildren,
  CampaignsCreateRoute: CampaignsCreateRoute,
  MyReportsIdRoute: MyReportsIdRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  MyReportsIndexRoute: MyReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
