create extension if not exists pgcrypto;

create table wards (
  id bigint generated by default as identity primary key,
  ward_code varchar(50) not null unique,
  name varchar(255) not null unique,
  type varchar(30) not null check (type in ('WARD', 'COMMUNE')),
  city_name varchar(100) not null default 'Da Nang',
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table users (
  id bigint generated by default as identity primary key,
  username varchar(100) not null unique,
  password varchar(255) not null,
  full_name varchar(100) not null,
  phone_number varchar(20) unique,
  email varchar(100) unique,
  role varchar(20) not null check (role in ('CITIZEN', 'WARD_STAFF', 'POLICE', 'SUPER_ADMIN')),
  status varchar(20) not null default 'ACTIVE' check (status in ('ACTIVE', 'LOCKED', 'INACTIVE')),
  ward_id bigint references wards(id) on delete set null,
  citizen_id_card varchar(50) unique,
  is_phone_verified boolean not null default false,
  is_identity_verified boolean not null default false,
  mfa_secret text,
  is_mfa_enabled boolean not null default false,
  login_attempts int not null default 0,
  locked_until timestamptz,
  deleted_at timestamptz,
  deleted_by varchar(100),
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  created_by varchar(255)
);

create table categories (
  id bigint generated by default as identity primary key,
  name varchar(255) not null unique,
  description text,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table feedbacks (
  id bigint generated by default as identity primary key,
  tracking_code varchar(20) not null unique,
  citizen_id bigint not null references users(id) on delete restrict,
  ward_id bigint not null references wards(id) on delete restrict,
  category_id bigint references categories(id) on delete set null,
  title varchar(255) not null,
  description text not null,
  latitude double precision,
  longitude double precision,
  address_details varchar(255),
  receiver_type varchar(20) not null check (receiver_type in ('WARD_STAFF', 'POLICE')),
  status varchar(20) not null default 'PENDING'
    check (status in ('PENDING', 'IN_PROGRESS', 'WAITING_INFO', 'RESOLVED', 'REJECTED')),
  priority varchar(20) not null default 'MEDIUM'
    check (priority in ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
  source varchar(30) default 'CITIZEN_APP'
    check (source in ('CITIZEN_APP', 'WEB', 'STAFF_CREATED')),
  resolved_at timestamptz,
  resolution_note text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  created_by varchar(255)
);

create table attachments (
  id bigint generated by default as identity primary key,
  feedback_id bigint not null references feedbacks(id) on delete cascade,
  file_url varchar(500) not null,
  file_type varchar(50) not null check (file_type in ('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT')),
  file_name varchar(255),
  file_size bigint,
  uploaded_by bigint references users(id) on delete set null,
  uploaded_at timestamptz default now()
);

create table feedback_logs (
  id bigint generated by default as identity primary key,
  feedback_id bigint not null references feedbacks(id) on delete cascade,
  action_by_id bigint not null references users(id) on delete restrict,
  action varchar(50) not null
    check (action in ('CREATE', 'AI_ROUTE', 'MANUAL_ROUTE', 'UPDATE_STATUS', 'REQUEST_INFO', 'RESOLVE', 'REJECT')),
  old_status varchar(20),
  new_status varchar(20),
  note text,
  created_at timestamptz default now()
);

create table ai_analysis (
  id bigint generated by default as identity primary key,
  feedback_id bigint not null unique references feedbacks(id) on delete cascade,
  suggested_ward_id bigint references wards(id) on delete set null,
  suggested_category_id bigint references categories(id) on delete set null,
  suggested_priority varchar(20) check (suggested_priority in ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
  suggested_receiver_type varchar(20) check (suggested_receiver_type in ('WARD_STAFF', 'POLICE')),
  confidence_score double precision,
  location_reason text,
  category_reason text,
  raw_result text,
  is_applied boolean not null default false,
  created_at timestamptz default now()
);

create table notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  title varchar(255) not null,
  content text not null,
  type varchar(50) default 'SYSTEM',
  reference_id bigint,
  is_read boolean not null default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table refresh_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id bigint not null references users(id) on delete cascade,
  token_hash varchar(64) not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  used boolean not null default false,
  used_at timestamptz
);

create table sms_verifications (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete cascade,
  phone_number varchar(20) not null,
  otp_code varchar(10) not null,
  purpose varchar(30) not null check (purpose in ('REGISTER', 'LOGIN', 'RESET_PASSWORD', 'CHANGE_PHONE')),
  expires_at timestamptz not null,
  verified_at timestamptz,
  is_used boolean not null default false,
  attempts int not null default 0,
  created_at timestamptz default now()
);

create table chat_history (
  id uuid primary key default gen_random_uuid(),
  user_id bigint not null references users(id) on delete cascade,
  question text not null,
  answer text,
  doc_type varchar(50) default 'danang-policy',
  ai_provider varchar(30) default 'GROQ',
  latency_ms bigint default 0,
  created_at timestamptz default now()
);

create table knowledge_base (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  category varchar(100),
  created_by bigint references users(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table feedback_evaluations (
  id bigint generated by default as identity primary key,
  feedback_id bigint not null unique references feedbacks(id) on delete cascade,
  citizen_id bigint not null references users(id) on delete restrict,
  rating int not null check (rating between 1 and 5),
  comment text,
  created_at timestamptz default now()
);

create table campaigns (
  id bigint generated by default as identity primary key,
  created_by bigint not null references users(id) on delete restrict,
  ward_id bigint references wards(id) on delete set null,
  title varchar(255) not null,
  description text,
  location_text varchar(255),
  latitude double precision,
  longitude double precision,
  max_participants int,
  start_time timestamptz,
  end_time timestamptz,
  status varchar(20) not null default 'PENDING'
    check (status in ('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table campaign_participants (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references campaigns(id) on delete cascade,
  citizen_id bigint not null references users(id) on delete cascade,
  join_status varchar(20) not null default 'SURE'
    check (join_status in ('SURE', 'NOT_SURE', 'CANCELLED')),
  cancelled_at timestamptz,
  created_at timestamptz default now(),
  unique (campaign_id, citizen_id)
);

create table campaign_chat_messages (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references campaigns(id) on delete cascade,
  sender_id bigint not null references users(id) on delete cascade,
  message text not null,
  created_at timestamptz default now()
);

create table regional_warnings (
  id bigint generated by default as identity primary key,
  issued_by bigint not null references users(id) on delete restrict,
  ward_id bigint references wards(id) on delete set null,
  title varchar(255) not null,
  content text not null,
  warning_level varchar(20) not null default 'NORMAL'
    check (warning_level in ('NORMAL', 'HIGH', 'EMERGENCY')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table kpi_reports (
  id bigint generated by default as identity primary key,
  created_by bigint not null references users(id) on delete restrict,
  ward_id bigint references wards(id) on delete set null,
  report_type varchar(100),
  title varchar(255) not null,
  file_url varchar(500),
  created_at timestamptz default now()
);

create index idx_users_ward_id on users(ward_id);
create index idx_feedbacks_citizen_id on feedbacks(citizen_id);
create index idx_feedbacks_ward_status on feedbacks(ward_id, status);
create index idx_feedbacks_receiver_type on feedbacks(receiver_type);
create index idx_attachments_feedback_id on attachments(feedback_id);
create index idx_feedback_logs_feedback_id on feedback_logs(feedback_id);
create index idx_notifications_user_read on notifications(user_id, is_read);
create index idx_refresh_tokens_user_id on refresh_tokens(user_id);
create index idx_refresh_tokens_expires_at on refresh_tokens(expires_at);
create index idx_sms_phone_purpose on sms_verifications(phone_number, purpose);
create index idx_chat_history_user_id on chat_history(user_id);
create index idx_campaign_participants_campaign_id on campaign_participants(campaign_id);
create index idx_campaign_chat_messages_campaign_id on campaign_chat_messages(campaign_id);
create index idx_regional_warnings_ward_id on regional_warnings(ward_id);
create index idx_kpi_reports_ward_id on kpi_reports(ward_id);
